title = "q"
tagline = "Runtime typechecker for Roblox"

gitSourceBranch = "master"
changelog = false

[docusaurus]
url = "https://realnickk.github.io"
baseUrl = "/q/"

[footer]
style = "dark"
copyright = "Copyright © 2021 RealNickk. Built with Moonwave and Docusaurus"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Flexible"
description = "q is a flexible, easy to use, and powerful runtime typechecker for Lua. It can be used to check the types of arguments, return values, and variables."

[[home.features]]
title = "Compatible"
description = "This library has measures in place to ensure that the most popular versions of Lua are supported, mainly kept around the Roblox scope."

[[home.features]]
title = "Dynamic"
description = "q is a dynamic typechecker, meaning that it can check the types of arguments, return values, and variables at runtime, and not just at compile time."